---
version: "3.8"
services:
  sync:
    container_name: sync
    image: sync:latest
    env_file:
      - ./.env
    user: ${USERID}:${GROUPID}
    volumes:
      - ./logs:/logs
      - ./backup:/backup

  filebrowser:
    image: hurlenko/filebrowser
    user: "${USERID}:${GROUPID}"
    restart: unless-stopped
    container_name: filebrowser
    volumes:
      - ${HOME}:/data
      - ./filebrowser_config:/config
    ports:
      - 8080:8080
    environment:
      - FB_BASEURL=/filebrowser

  wetty:
    container_name: wetty
    image: wettyoss/wetty:2.5.0
    user: ${USERID}:${GROUPID}
    ports:
      - 3333:3000
    environment:
      - SSHHOST=172.17.0.1
      - SSHUSER=pi
