---
services:
  sync:
    container_name: sync
    image: sync:latest
    user: ${USERID}:${GROUPID}
    volumes:
      - ./logs:/logs
      - ./backup:/backup
      - ./configs/config.toml:/config.toml
      - ./configs/sync_logging_config.json:/sync_logging_config.json

  filebrowser:
    image: hurlenko/filebrowser
    user: "${USERID}:${GROUPID}"
    restart: unless-stopped
    container_name: filebrowser
    volumes:
      - ${HOME}:/data
      - ./configs/filebrowser_config:/config
    ports:
      - 8080:8080
    environment:
      - FB_BASEURL=/filebrowser

  wetty:
    container_name: wetty
    image: wettyoss/wetty:2.5.0
    user: ${USERID}:${GROUPID}
    ports:
      - 3333:3000
    environment:
      - SSHHOST=172.17.0.1
      - SSHUSER=pi
